services:
    # PHP application service
    app:
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
            args:
                UID: ${UID:-1000}
                GID: ${GID:-1000}
        container_name: pagabem-app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - './:/var/www'
        networks:
            - pagabem-network
        depends_on:
            - mysql
            - redis
    # Nginx web server service
    nginx:
        image: 'nginx:1.25-alpine'
        container_name: pagabem-nginx
        restart: unless-stopped
        ports:
            - '8000:80'
        volumes:
            - './:/var/www'
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - pagabem-network
        depends_on:
            - app
        expose:
            - '8000'
        links:
          - app

    # MySQL database service
    mysql:
        image: 'mysql:8.0'
        container_name: pagabem-db
        restart: unless-stopped
        ports:
            - '3306:3306'
        environment:
            MYSQL_DATABASE: '${DB_DATABASE:-pagabem}'
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD:-password}'
            MYSQL_USER: '${DB_USERNAME:-user}'
            MYSQL_PASSWORD: '${DB_PASSWORD:-userpass}'
        volumes:
            - 'pagabem-db-data:/var/lib/mysql'
        networks:
            - pagabem-network
        expose:
            - '3306'

    # Redis service queue and cache driver
    redis:
        image: 'redis:7-alpine'
        container_name: pagabem-redis
        restart: unless-stopped
        networks:
            - pagabem-network

    # Laravel Queue Worker to process jobs (mainly the notification service)
    queue-worker:
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
            args:
                UID: ${UID:-1000}
                GID: ${GID:-1000}
        restart: always
        working_dir: /var/www
        volumes:
            - './:/var/www'
        command: 'php artisan queue:work --tries=3'
        networks:
            - pagabem-network
        depends_on:
            - app
            - redis
            - mysql
        deploy:
            replicas: 3
            
networks:
    pagabem-network:
        driver: bridge
volumes:
    pagabem-db-data:
        driver: local
